version: 0.0
os: linux
files:
  - source: /
    destination: /opt/api-codedeploy
hooks:
  BeforeInstall:
    - location: deployment/scripts/system_install.sh
      timeout: 700
      runas: root
    - location: deployment/scripts/tomcat_install.sh
      timeout: 700
      runas: root
    - location: deployment/scripts/maintenance_enable.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deployment/scripts/tomcat_configure.sh
      timeout: 300
      runas: root
    - location: deployment/scripts/deployment.sh
      timeout: 700
      runas: root
  ApplicationStart:
    - location: deployment/scripts/maintenance_disable.sh
      timeout: 300
      runas: root
